version: '3.9'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tvarah-app
    env_file:
      - ../.env
    ports:
      - "8201:8201"
    extra_hosts:
      - "host.docker.internal:host-gateway"
