FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN addgroup -S tvarah && adduser -S tvarah -G tvarah

COPY tvarah-1.0.0-SNAPSHOT.jar app.jar

RUN chown tvarah:tvarah app.jar
USER tvarah

EXPOSE 8201

ENTRYPOINT ["java", \
  "-XX:+UseContainerSupport", \
  "-XX:MaxRAMPercentage=75.0", \
  "-jar", "app.jar"]
